export const SET_STATUS_FILTER_BOX_VALUE = 'SET_STATUS_FILTER_BOX_VALUE';

export const GET_APPOINTMENTS_SUCCESS = 'GET_APPOINTMENTS_SUCCESS';

export const GET_APPOINTMENTS = 'GET_APPOINTMENTS';

export const GET_APPOINTMENTS_FAILED = 'GET_APPOINTMENTS_FAILED';
