export const SET_STATUS_FILTER_BOX_VALUE = 'SET_STATUS_FILTER_BOX_VALUE';

export const GET_PATIENTS_DATA_SUCCESS = 'GET_PATIENTS_DATA_SUCCESS';

export const GET_PATIENTS_DATA = 'GET_PATIENTS_DATA';

export const GET_PATIENTS_DATA_FAILED = 'GET_PATIENTS_DATA_FAILED';
