export const SET_ACTIVE_PATIENT = 'SET_ACTIVE_PATIENT';
export const SET_ACTIVE_ENCOUNTER = 'SET_ACTIVE_ENCOUNTER';
export const SET_ACTIVE_ENCOUNTER_AND_PATIENT =
  'SET_ACTIVE_ENCOUNTER_AND_PATIENT';
