export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_EXPIRED = 'LOGIN_EXPIRED';
export const MFA_REQUIRED = 'MFA_REQUIRED';

export const LOGOUT_START = 'LOG_OUT_START';
export const LOGOUT_SUCCESS = 'LOG_OUT_SUCCESS';
export const LOGOUT_FAILED = 'LOG_OUT_FAILED';
