export const GET_SETTINGS = 'GET_SETTINGS';
export const GET_SETTINGS_SUCCESS = 'GET_SETTINGS_SUCCESS';
export const GET_SETTINGS_FAILED = 'GET_SETTINGS_FAILED';

export const SET_SETTINGS = 'SET_SETTINGS';
export const SET_SETTINGS_FAILED = 'SET_SETTINGS_FAILED';
export const SET_SETTINGS_SUCCESS = 'SET_SETTINGS_SUCCESS';
