export const SET_APPOINTMENTS_WITH_PATIENTS = 'SET_APPOINTMENTS_WITH_PATIENTS';
export const SET_APPOINTMENTS_WITH_PATIENTS_SUCCESS = 'SET_APPOINTMENTS_WITH_PATIENTS_SUCCESS';
export const SET_APPOINTMENTS_WITH_PATIENTS_FAILED = 'SET_APPOINTMENTS_WITH_PATIENTS_FAILED';

export const SET_ENCOUNTER_WITH_PATIENTS = 'SET_ENCOUNTER_WITH_PATIENT';
export const SET_ENCOUNTER_WITH_PATIENTS_SUCCESS = 'SET_ENCOUNTER_WITH_PATIENT_SUCCES';
export const SET_ENCOUNTER_WITH_PATIENTS_FAILED = 'SET_ENCOUNTER_WITH_PATIENT_FAILED';

export const UPDATE_APPOINTMENT = 'UPDATE_APPOINTMENT';
export const UPDATE_APPOINTMENT_SUCCESS = 'UPDATE_APPOINTMENT_SUCCESS';
export const UPDATE_APPOINTMENT_FAILED = 'UPDATE_APPOINTMENT_FAILED'; 