export const SET_FILTER_DATE = 'SET_FILTER_DATE';
export const SET_ORGANIZATION_FILTER_VALUE = 'SET_ORGANIZATION_FILTER_VALUE';
export const SET_SERVICE_TYPE_FILTER_VALUE = 'SET_SERVICE_TYPE_FILTER_VALUE';
